import scipy.stats


# some distributions were excluded because they were:
# * deprecated
# * raising errors during fitting
# * taking ages to fit (levy_stable)
names = [
    'alpha',
    'anglit',
    'arcsine',
    'argus',
    'beta',
    'betaprime',
    'bradford',
    'burr',
    'burr12',
    'cauchy',
    'chi',
    'chi2',
    'cosine',
    'crystalball',
    'dgamma',
    'dweibull',
    'expon',
    'exponnorm',
    'exponpow',
    'exponweib',
    'f',
    'fatiguelife',
    'fisk',
    'foldcauchy',
    'foldnorm',
    'gamma',
    'gausshyper',
    'genexpon',
    'genextreme',
    'gengamma',
    'genhalflogistic',
    'geninvgauss',
    'genlogistic',
    'gennorm',
    'genpareto',
    'gilbrat',
    'gompertz',
    'gumbel_l',
    'gumbel_r',
    'halfcauchy',
    'halfgennorm',
    'halflogistic',
    'halfnorm',
    'hypsecant',
    'invgamma',
    'invgauss',
    'invweibull',
    'johnsonsb',
    'johnsonsu',
    'kappa3',
    'kappa4',
    'laplace',
    'levy',
    'levy_l',
    'loggamma',
    'logistic',
    'loglaplace',
    'lognorm',
    'loguniform',
    'lomax',
    'maxwell',
    'mielke',
    'moyal',
    'nakagami',
    'ncf',
    'nct',
    'ncx2',
    'norm',
    'norminvgauss',
    'pareto',
    'pearson3',
    'powerlaw',
    'powerlognorm',
    'powernorm',
    'rayleigh',
    'rdist',
    'recipinvgauss',
    'reciprocal',
    'rice',
    'semicircular',
    'skewnorm',
    't',
    'trapz',
    'triang',
    'truncexpon',
    'truncnorm',
    'tukeylambda',
    'uniform',
    'vonmises',
    'vonmises_line',
    'wald',
    'weibull_max',
    'weibull_min',
    'wrapcauchy',
]
distributions = {
    name: getattr(scipy.stats, name)
    for name in names
    if hasattr(scipy.stats, name) # older versions miss some distributions
}
